[2024-05-06T03:38:58.728+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_prediction_2.train_model manual__2024-05-06T03:37:46.912781+00:00 [queued]>
[2024-05-06T03:38:58.836+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_prediction_2.train_model manual__2024-05-06T03:37:46.912781+00:00 [queued]>
[2024-05-06T03:38:58.837+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-05-06T03:38:59.218+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): train_model> on 2024-05-06 03:37:46.912781+00:00
[2024-05-06T03:38:59.303+0000] {standard_task_runner.py:57} INFO - Started process 356 to run task
[2024-05-06T03:38:59.331+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'diabetes_prediction_2', 'train_model', 'manual__2024-05-06T03:37:46.912781+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmp0qfjloul']
[2024-05-06T03:38:59.335+0000] {standard_task_runner.py:85} INFO - Job 279: Subtask train_model
[2024-05-06T03:38:59.590+0000] {task_command.py:410} INFO - Running <TaskInstance: diabetes_prediction_2.train_model manual__2024-05-06T03:37:46.912781+00:00 [running]> on host 18590e1a4d2d
[2024-05-06T03:39:00.090+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_prediction_2' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T03:37:46.912781+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T03:37:46.912781+00:00'
[2024-05-06T03:39:05.010+0000] {logging_mixin.py:149} WARNING - 2024/05/06 03:39:04 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-05-06T04:02:42.282+0000] {logging_mixin.py:149} WARNING - 2024/05/06 04:02:42 WARNING mlflow.sklearn.utils: Failed to import matplotlib (error: ModuleNotFoundError("No module named 'matplotlib'")). Skipping artifact logging.
[2024-05-06T04:02:42.393+0000] {logging_mixin.py:149} WARNING - 2024/05/06 04:02:42 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.7/site-packages/mlflow/models/signature.py:129: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2024-05-06T04:02:42.416+0000] {logging_mixin.py:149} WARNING - 2024/05/06 04:02:42 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: Cell is empty
[2024-05-06T04:02:51.281+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

[2024-05-06T04:02:51.367+0000] {logging_mixin.py:149} INFO - Mejores hiperparámetros: {'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}
[2024-05-06T04:02:51.367+0000] {logging_mixin.py:149} INFO - Mejor puntuación de CV: 0.5655643516283768
[2024-05-06T04:02:51.421+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-05-06T04:02:51.462+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=diabetes_prediction_2, task_id=train_model, execution_date=20240506T033746, start_date=20240506T033858, end_date=20240506T040251
[2024-05-06T04:02:51.554+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-05-06T04:02:51.599+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
