[2024-05-05T00:00:24.821+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_prediction.train_model scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-05T00:00:24.850+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_prediction.train_model scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-05T00:00:24.850+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-05-05T00:00:24.896+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): train_model> on 2024-05-04 00:00:00+00:00
[2024-05-05T00:00:24.916+0000] {standard_task_runner.py:57} INFO - Started process 9874 to run task
[2024-05-05T00:00:24.924+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'diabetes_prediction', 'train_model', 'scheduled__2024-05-04T00:00:00+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpr0k76x8r']
[2024-05-05T00:00:24.925+0000] {standard_task_runner.py:85} INFO - Job 258: Subtask train_model
[2024-05-05T00:00:25.155+0000] {task_command.py:410} INFO - Running <TaskInstance: diabetes_prediction.train_model scheduled__2024-05-04T00:00:00+00:00 [running]> on host 9c8b03f5e67f
[2024-05-05T00:00:25.493+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_prediction' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-04T00:00:00+00:00'
[2024-05-05T00:00:26.767+0000] {logging_mixin.py:149} WARNING - 2024/05/05 00:00:26 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-05-05T00:00:33.385+0000] {logging_and_warnings.py:72} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

[2024-05-05T00:00:33.831+0000] {logging_mixin.py:149} WARNING - 2024/05/05 00:00:33 WARNING mlflow.sklearn.utils: Failed to import matplotlib (error: ModuleNotFoundError("No module named 'matplotlib'")). Skipping artifact logging.
[2024-05-05T00:00:33.981+0000] {logging_mixin.py:149} WARNING - 2024/05/05 00:00:33 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.7/site-packages/mlflow/models/signature.py:129: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2024-05-05T00:00:39.692+0000] {logging_mixin.py:149} WARNING - 2024/05/05 00:00:39 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2024-05-05T00:00:43.685+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-05-05T00:00:43.711+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=diabetes_prediction, task_id=train_model, execution_date=20240504T000000, start_date=20240505T000024, end_date=20240505T000043
[2024-05-05T00:00:43.785+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2024-05-05T00:00:43.828+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
