[2024-05-01T15:57:21.173+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_prediction.fetch_dataset manual__2024-05-01T15:57:16.341209+00:00 [queued]>
[2024-05-01T15:57:21.193+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_prediction.fetch_dataset manual__2024-05-01T15:57:16.341209+00:00 [queued]>
[2024-05-01T15:57:21.194+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-05-01T15:57:21.230+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): fetch_dataset> on 2024-05-01 15:57:16.341209+00:00
[2024-05-01T15:57:21.243+0000] {standard_task_runner.py:57} INFO - Started process 413 to run task
[2024-05-01T15:57:21.252+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'diabetes_prediction', 'fetch_dataset', 'manual__2024-05-01T15:57:16.341209+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp1129l8jz']
[2024-05-01T15:57:21.257+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask fetch_dataset
[2024-05-01T15:57:21.359+0000] {task_command.py:410} INFO - Running <TaskInstance: diabetes_prediction.fetch_dataset manual__2024-05-01T15:57:16.341209+00:00 [running]> on host c90068845469
[2024-05-01T15:57:21.562+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_prediction' AIRFLOW_CTX_TASK_ID='fetch_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T15:57:16.341209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T15:57:16.341209+00:00'
[2024-05-01T15:57:23.265+0000] {warnings.py:110} WARNING - /opt/***/dags/dag1.py:15: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  data = fetch_ucirepo(id=296)

[2024-05-01T15:57:23.391+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag1.py", line 17, in fetch_dataset
    kwargs['ti'].xcom_push(key='dataframe', value=data)
NameError: name 'kwargs' is not defined
[2024-05-01T15:57:23.411+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=diabetes_prediction, task_id=fetch_dataset, execution_date=20240501T155716, start_date=20240501T155721, end_date=20240501T155723
[2024-05-01T15:57:23.438+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 28 for task fetch_dataset (name 'kwargs' is not defined; 413)
[2024-05-01T15:57:23.480+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2024-05-01T15:57:23.532+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
