[2024-05-01T16:20:23.523+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_prediction.preprocess_data manual__2024-05-01T16:20:08.691830+00:00 [queued]>
[2024-05-01T16:20:23.544+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_prediction.preprocess_data manual__2024-05-01T16:20:08.691830+00:00 [queued]>
[2024-05-01T16:20:23.544+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-05-01T16:20:23.572+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2024-05-01 16:20:08.691830+00:00
[2024-05-01T16:20:23.585+0000] {standard_task_runner.py:57} INFO - Started process 852 to run task
[2024-05-01T16:20:23.592+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'diabetes_prediction', 'preprocess_data', 'manual__2024-05-01T16:20:08.691830+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp0zibxaj3']
[2024-05-01T16:20:23.596+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask preprocess_data
[2024-05-01T16:20:23.686+0000] {task_command.py:410} INFO - Running <TaskInstance: diabetes_prediction.preprocess_data manual__2024-05-01T16:20:08.691830+00:00 [running]> on host c90068845469
[2024-05-01T16:20:23.862+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_prediction' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T16:20:08.691830+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T16:20:08.691830+00:00'
[2024-05-01T16:20:24.348+0000] {logging_mixin.py:149} INFO - 1
[2024-05-01T16:20:24.348+0000] {logging_mixin.py:149} INFO - <class 'pandas.core.frame.DataFrame'>
[2024-05-01T16:20:25.612+0000] {xcom.py:640} ERROR - Object of type tuple is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-05-01T16:20:25.615+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/serialization/serde.py", line 144, in serialize
    return encode(classname, version, serialize(data, depth + 1))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/serialization/serde.py", line 123, in serialize
    return [serialize(d, depth + 1) for d in o]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/serialization/serde.py", line 123, in <listcomp>
    return [serialize(d, depth + 1) for d in o]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/serialization/serde.py", line 171, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas.core.series.Series'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag1.py", line 43, in preprocess_data
    ti.xcom_push(key='preprocessed_data', value=(df3, y2))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2384, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 243, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 632, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 102, in encode
    o = self.default(o)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type tuple is not JSON serializable
[2024-05-01T16:20:25.636+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=diabetes_prediction, task_id=preprocess_data, execution_date=20240501T162008, start_date=20240501T162023, end_date=20240501T162025
[2024-05-01T16:20:25.665+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 38 for task preprocess_data (Object of type tuple is not JSON serializable; 852)
[2024-05-01T16:20:25.700+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2024-05-01T16:20:25.758+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
